### ISSUE TITLE
`css` config param

### ISSUE THREAD

**Issue by eric-h-st** [mykle1/MMM-Climacell-Hourly#1]
Hi,

Great module!

I'm trying to alter the `css` config parameter but it's doing nothing. I debugged into `getStyles` to see that it does return the desired css file, but see no visual difference.

What am I missing?

Thank you.

**Comment by mykle1** [comment]
You're not missing anything. I fucked up. I'll fix it by tomorrow or the latest by Saturday

**Comment by eric-h-st** [comment]
Thank you!

**Comment by mykle1** [comment]
I'm gonna upload the fix now. Do a 'git pull' in the MMM-Climacell-Hourly directory to get the new files

**Comment by eric-h-st** [comment]
Thank you. It's working now, and I was able to add a Star Trek theme :-)
