### ISSUE TITLE
MMM-Climacell-Hourly by mykle1. Climacell data...

### ISSUE THREAD

**Issue by Mateo193** [mykle1/MMM-Climacell-Hourly#2]
Hello i have problem with module MMM-Climacell-Hourly by mykle1
logs:

> 0|MagicMirror  | Checking git for module: MMM-Climacell-Hourly
> 0|MagicMirror  | [2021-01-26 16:48:17.099] [INFO]
> 0|MagicMirror  | Checking git for module: MMM-Screencast
> 0|MagicMirror  | [2021-01-26 16:48:17.958] [ERROR]
> 0|MagicMirror  | Whoops! There was an uncaught exception...
> 0|MagicMirror  | [2021-01-26 16:48:17.963] [ERROR]
> 0|MagicMirror  | TypeError: result.slice is not a function
> 0|MagicMirror  |     at Request._callback (/home/pi/MagicMirror/modules/MMM-Climacell-Hourly/node_helper.js:46:33)
> 0|MagicMirror  |     at Request.self.callback (/home/pi/MagicMirror/node_modules/request/request.js:185:22)
> 0|MagicMirror  |     at Request.emit (events.js:200:13)
> 0|MagicMirror  |     at Request.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1154:10)
> 0|MagicMirror  |     at Request.emit (events.js:200:13)
> 0|MagicMirror  |     at IncomingMessage.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1076:12)
> 0|MagicMirror  |     at Object.onceWrapper (events.js:288:20)
> 0|MagicMirror  |     at IncomingMessage.emit (events.js:205:15)
> 0|MagicMirror  |     at endReadableNT (_stream_readable.js:1154:12)
> 0|MagicMirror  |     at processTicksAndRejections (internal/process/task_queues.js:84:9)
> 0|MagicMirror  | [2021-01-26 16:48:17.970] [ERROR]
> 0|MagicMirror  | MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
> 0|MagicMirror  | [2021-01-26 16:48:17.973] [ERROR]  If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

[Foto and config.js](https://imgur.com/EMNFLP0)

**Comment by mykle1** [comment]
Yes, I am aware of the problem. Climacel recently moved to v4 of their api. This module was written using the v3 protocols. I am in the process of fixing MMM-BMW-CC. When that is completed I will start working on this module.

**Comment by mykle1** [comment]
Finished fixing MMM-BMW-CC. Give me a few days to complete fixing this one now. Thanks for your interest and patience.

**Comment by Mateo193** [comment]
THank you for the quick reaply. Of couse, i will wait.

**Comment by mykle1** [comment]
Do a git pull in the MagicMirror directory or install as usual.

This issue is now closed.

Remember to get a new API key from climacell as older one's will not work with the new v4 API
